version: "{build}"
build: off
deploy: off

environment:
  matrix:
    - nodejs_version: 'stable'
    - nodejs_version: 'lts/*'
    - nodejs_version: 6

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
